name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: # Steps must be indented under the job name
      - name: Checkout code
        uses: actions/checkout@v4 # Use v4 (latest stable)

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Use v4
        with:
          node-version: 20 # Using a modern LTS version

      - name: Install dependencies
        run: npm install # 'npm i' works too, but 'install' is clearer for logs

      - name: Run tests
        run: npm test